version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
