version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - sphinx-apidoc -o docs/ xclim

python:
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
