name: xclim
channels:
    - conda-forge
    - defaults
dependencies:
    - python >=3.9,<3.12
    - astroid
    - boltons >=20.1
    - bottleneck >=1.3.1
    - cf_xarray >=0.6.1
    - cftime >=1.4.1
    - Click >=8.1
    - dask >=2.6.0
    - jsonpickle
    - lmoments3
    - numba
    - numpy >=1.16
    - pandas >=2.1  # This should be raised to Pandas 2.2 when released
    - pint >=0.9
    - poppler >=0.67
    - pyyaml
    - scikit-learn >=0.21.3
    - scipy >=1.2
    - statsmodels
    - xarray >=2023.11.0
    # Extras
    - eofs
    - flox
  # Testing and development dependencies
    - black >=22.12
    - blackdoc
    - bump-my-version
    - cairosvg
    - codespell
    - coverage
    - distributed >=2.0
    - filelock
    - flake8
    - flake8-rst-docstrings
    - flit
    - h5netcdf
    - ipykernel
    - ipython
    - matplotlib
    - mypy
    - nbqa
    - nbsphinx
    - nbval
    - nc-time-axis
    - netCDF4 >=1.4
    - notebook
    - platformdirs
    - pooch
    - pre-commit
    - pybtex
    - pylint
    - pytest
    - pytest-cov
    - pytest-socket
    - pytest-xdist >=3.2
    - ruff >=0.1.0
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-codeautolink
    - sphinx-copybutton
    - sphinx-rtd-theme >=1.0
    - sphinxcontrib-bibtex
    - tokenize-rt
    - tox
#    - tox-conda  # Will be added when a tox@v4.0+ compatible plugin is released.
    - xdoctest
    - yamale
    - yamllint
    - pip
    - pip:
        - flake8-alphabetize
        - sphinxcontrib-svg2pdfconverter
