name: xclim
channels:
 - conda-forge
 - defaults
dependencies:
 - scipy>=1.2
 - numpy>=1.17
 - pandas>=0.23
 - cftime>=1.0.4.2
 - netCDF4<1.5.3
 - dask>=2.8.0
 - bottleneck>=1.3.1
 - xarray>=0.14.1
 - pyproj>=2.4.1
 - pint>=0.9
 - boltons>=19.2
 - scikit-learn>=0.21.3
