name: xclim
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.8
    - astroid
    - boltons>=20.1
    - bottleneck>=1.3.1
    - cf_xarray>=0.6.1
    - cftime>=1.4.1
    - Click >=8.1
    - dask>=2.6.0
    - jsonpickle
    - numba
    - numpy>=1.16
    - pandas>=0.23
    - pint>=0.9
    - poppler>=0.67
    - pyyaml
    - scikit-learn>=0.21.3
    - scipy>=1.2,<1.9  # See https://github.com/Ouranosinc/xclim/issues/1142
    - xarray>=2022.06.0
    # Extras
    - eofs
    - eigen
    - pybind11
