name: xclim
channels:
  - numba  # Added to gain access to Python3.12-compatible numba release candidates.
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - astroid
  - boltons >=20.1
  - bottleneck >=1.3.1
  - cf_xarray >=0.6.1
  - cftime >=1.4.1
  - Click >=8.1
  - dask >=2.6.0
  - importlib-resources  # For Python3.8
  - jsonpickle
  - lmoments3
  - numba
  - numpy >=1.16
  - pandas >=0.23,<2.2
  - pint >=0.9
  - poppler >=0.67
  - pyyaml
  - scikit-learn >=0.21.3
  - scipy >=1.2
  - statsmodels
  - xarray >=2022.06.0,<2023.11.0
  - yamale
  # Extras
  - flox
  # Testing and development dependencies
  - black ==24.1.0
  - blackdoc ==0.3.9
#  - bump-my-version  # The conda package is not as up-to-date as the PyPI package.
  - cairosvg
  - codespell
  - coverage
  - distributed >=2.0
  - filelock
  - flake8
  - flake8-rst-docstrings
  - flit
  - h5netcdf
  - ipykernel
  - ipython
  - isort ==5.13.2
  - matplotlib
  - mypy
  - nbqa
  - nbsphinx
  - nbval
  - nc-time-axis
  - netCDF4 >=1.4
  - notebook
  - platformdirs
  - pooch
  - pre-commit
  - pybtex
  - pylint
  - pytest
  - pytest-cov
  - pytest-socket
  - pytest-xdist >=3.2
  - ruff >=0.1.0
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-rtd-theme >=1.0
  - sphinxcontrib-bibtex
  - tokenize-rt
  - tox >=4.0
#  - tox-conda  # Will be added when a tox@v4.0+ compatible plugin is released.
  - xdoctest
  - yamllint
  - pip
  - pip:
    - bump-my-version >=0.17.1  # The conda package is not as up-to-date as the PyPI package.
    - flake8-alphabetize
    - sphinxcontrib-svg2pdfconverter
