name: xclim-demo
channels:
 - conda-forge
 - defaults
dependencies:
  - jupyter
  # xclim[docs]
  - xclim==0.26
  - matplotlib
  - nc-time-axis
  - distributed>=2.0
  - pooch
  # For visualisation
  - hvplot
  # For finch
  - birdy
  - cftime
  - pywps==4.4
  - xarray==0.17.0
  - xesmf>=0.5.3
  - clisops>=0.6.1
  - geopandas
  - jinja2
  - click
  - psutil
  - bottleneck
  - netcdf4
  - numpy
  - unidecode
  - dask[complete]
  - scipy
  - requests
  - sentry-sdk
  - siphon
  - parse
  - pip
  - pip:
    - git+https://github.com/bird-house/finch.git@v0.7.4#egg=finch
