name: Add Issues to xclim Project

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add Issue to xclim Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/Ouranosinc/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
