name: "xclim Doctests"

on:
  push:
    branches:
      - master
    paths-ignore:
      - HISTORY.rst
      - setup.cfg
      - setup.py
      - xclim/__init__.py
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  doctests:
    if: contains(github.event.pull_request.labels.*.name, 'approved')) || (github.event_name == "push")
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: pylint --rcfile=pylintrc --disable=import-error --exit-zero xclim
      - name: Install tox
        run: pip install tox
      - name: Run doctests
        run: tox -e doctests_only
