name: xclim

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: [black, doctests]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install tox
        run: pip install tox
      - name: Run lint
        run: tox -e ${{ matrix.tox-env }}

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: [py37-xarray, py38-slow]
        python-version: [3.7, 3.8]
        exclude:
          - tox-env: py37-xarray
            python-version: 3.8
          - tox-env: py38-slow
            python-version: 3.7
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: pip install tox
    - name: Test with tox
      run: tox -e ${{ matrix.tox-env }}

#  docs:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install packages
#        run: |
#          sudo apt-get -y install pandoc
#      - uses: actions/setup-python@v2
#        with:
#          python-version: 3.6
#      - name: Install tox
#        run: pip install tox
#      - name: make docs
#        run: tox -e docs

#    - name: Coveralls
#      uses: coverallsapp/github-action@master
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        flag-name: run-${{ matrix.python-version }}
#        parallel: true

#  finish:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#    - name: Coveralls Finished
#      uses: coverallsapp/github-action@master
#      with:
#        github-token: ${{ secrets.github_token }}
#        parallel-finished: true
