name: "xclim Simple Tests"

on:
  push:
    branches:
      - master
    paths-ignore:
      - HISTORY.rst
      - setup.cfg
      - setup.py
      - xclim/__init__.py
  pull_request:

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install tox
        run: pip install tox
      - name: Run linting suite
        run: tox -e black

  test-py38:
    needs: black
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install tox
        run: pip install tox
      - name: Test with tox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tox -e py38
      - name: report coverage
        if: |
          contains(github.event.pull_request.labels.*.name, 'approved') ||
          (github.event_name == 'push')
        uses: AndreMiras/coveralls-python-action@develop
        with:
          flag-name: run-py38
          parallel: true

  test-py39-sbck-slow-conda:
    needs: black
    if: |
      contains(github.event.pull_request.labels.*.name, 'approved') ||
      (github.event_name == 'push')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: sbck-experimental
          channels: conda-forge,defaults
          mamba-version: "*"
          python-version: "3.9"
      - name: Install tox
        shell: bash -l {0}
        run: mamba install -n sbck-experimental tox-conda tox
      - name: Test with tox
        shell: bash -l {0}
        run: |
          conda activate sbck-experimental
          tox -e sbck-slow
        env:
          CONDA_EXE: mamba
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: report coverage
        uses: AndreMiras/coveralls-python-action@develop
        with:
          flag-name: run-py39-sbck-slow-conda
          parallel: true

  test-py310-upstream-lm3:
    needs: black
    if: |
      contains(github.event.pull_request.labels.*.name, 'approved') ||
      (github.event_name == 'push')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Test with tox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tox -e py310-upstream-lm3
      - name: report coverage
        uses: AndreMiras/coveralls-python-action@develop
        with:
          flag-name: run-py310-upstream-lm3
          parallel: true

  finish:
    needs:
      - test-py310-upstream-lm3
      - test-py39-sbck-slow-conda
      - test-py38
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
