name: "xclim Documentation Build Test"

on:
  pull_request_target:
    types:
      - ready_for_review
  pull_request_review:
    types:
      - submitted

jobs:
  doctests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: pylint --rcfile=pylintrc --disable=import-error --exit-zero xclim
      - name: Install tox
        run: pip install tox
      - name: Run doctests
        run: tox -e doctests_only
