name: Publish Python 🐍 distributions 📦 to TestPyPI

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish-testpypi:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up Python3
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.x"
      - name: Install packaging libraries
        run: pip install flit
      - name: Build a binary wheel and a source tarball
        run: flit build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
