name: Publish Python 🐍 distributions 📦 to TestPyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish-testpypi:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    environment: staging
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Python3
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.x"
      - name: Install packaging libraries
        run: pip install flit
      - name: Build a binary wheel and a source tarball
        run: flit build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
